[tool.poetry]
name = "py_check"
version = "0.1.0"
description = ""
authors = ["Jake Williamson"]

[tool.poetry.dependencies]
python = "^3.10.8"
jupyter = "^1.1.1"
jupyter_core = "^5.7.2"
nbconvert = "^7.16.4"

[tool.poetry.dev-dependencies]
pytest = "8.3.2"
pylint = "3.3.1"
coverage = "7.6.1"
mypy = "1.13.0"
black = "24.10.0"
flake8 = "7.1.0"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"