[tool.poetry]
name = "py_check"
version = "0.1.0"
description = ""
authors = ["Jake Williamson"]

[tool.poetry.dependencies]
python = "^3.10.8"

[tool.poetry.dev-dependencies]
pytest = "8.2.0"
pylint = "3.1.0"
coverage = "7.4.0"
mypy = "1.9.0"
black = "24.3.0"
flake8 = "7.0.0"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"